require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - Gemfile
    - bin/*
    - db/schema.rb
    - db/migrate/*
    - config/**/*
    - config/environments/
    - spec/rails_helper.rb
    - spec/spec_helper.rb

Lint/EmptyBlock:
  Exclude:
    - spec/factories/devs.rb

Lint/MissingSuper:
  Exclude:
    - app/components/contact_component.rb
    - app/components/optional_component.rb

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - app/models/dev.rb
    - spec/**/*_spec.rb

Metrics/MethodLength:
  Exclude:
    - app/controllers/devs_controller.rb
    - app/models/dev.rb

Rails/OutputSafety:
  Exclude:
    - app/helpers/svg_helper.rb

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  Exclude:
    - spec/apis/github_api/v3/client_spec.rb

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
